### ISSUE TITLE
Sometimes image is not returned

### ISSUE THREAD

**Issue by darwinjob** [Neural-Systems-at-UIO/DZI-Scaler-Service#1]
Apparently it happens when CSCS returns 500 for some reason:

`18:54:06,593 ERROR [stderr] (default task-1) java.io.IOException: Server returned HTTP response code: 500 for URL: https://object.cscs.ch/v1/AUTH_08c08f9f119744cbbf77e216988da3eb/imgsvc-890b727c-f3b5-624f-028a-4f6d35acce18/D1R_P70_F_C60_s001.tif/D1R_P70_F_C60_s001.dzi 
18:54:06,594 ERROR [stderr] (default task-1) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
18:54:06,594 ERROR [stderr] (default task-1) 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
18:54:06,594 ERROR [stderr] (default task-1) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
18:54:06,594 ERROR [stderr] (default task-1) 	at java.net.URL.openStream(URL.java:1045)
18:54:06,594 ERROR [stderr] (default task-1) 	at no.uio.nesys.pyramidio.DziUrl.<init>(DziUrl.java:42)
18:54:06,594 ERROR [stderr] (default task-1) 	at no.uio.nesys.pyramidio.DeepZoomImageReaderUrl.<init>(DeepZoomImageReaderUrl.java:57)
18:54:06,594 ERROR [stderr] (default task-1) 	at no.uio.nesys.pyramidio.DeepZoomImageReaderUrl.<init>(DeepZoomImageReaderUrl.java:45)
18:54:06,594 ERROR [stderr] (default task-1) 	at no.uio.nesys.dziss.ScalerController.scaler(ScalerController.java:71)
18:54:06,594 ERROR [stderr] (default task-1) 	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
18:54:06,594 ERROR [stderr] (default task-1) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:54:06,595 ERROR [stderr] (default task-1) 	at java.lang.reflect.Method.invoke(Method.java:498)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
18:54:06,595 ERROR [stderr] (default task-1) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
18:54:06,595 ERROR [stderr] (default task-1) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
18:54:06,595 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
18:54:06,595 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
18:54:06,595 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
18:54:06,596 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
18:54:06,596 ERROR [stderr] (default task-1) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
18:54:06,597 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
18:54:06,597 ERROR [stderr] (default task-1) 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
18:54:06,598 ERROR [stderr] (default task-1) 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
18:54:06,598 ERROR [stderr] (default task-1) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
18:54:06,599 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
18:54:06,599 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
18:54:06,599 ERROR [stderr] (default task-1) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
18:54:06,599 ERROR [stderr] (default task-1) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
18:54:06,599 ERROR [stderr] (default task-1) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
18:54:06,599 ERROR [stderr] (default task-1) 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
18:54:06,599 ERROR [stderr] (default task-1) 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
18:54:06,599 ERROR [stderr] (default task-1) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
18:54:06,599 ERROR [stderr] (default task-1) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
18:54:06,599 ERROR [stderr] (default task-1) 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by darwinjob** [comment]
Reported to CSCS https://jira.cscs.ch/plugins/servlet/desk/portal/1/SD-53024

**Comment by darwinjob** [comment]
"We have in place a rate limiting mechanism to avoid service overloading.
Could you try to throttle down the request rate in your application and let us know how it goes?"

**Comment by darwinjob** [comment]
Improved (but not 100% fixed) in https://github.com/Neural-Systems-at-UIO/DZI-Scaler-Service/issues/2. Closing for now.
